// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.5
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container").wowSlider({
	effect:"turn,shift,louvers,cube_over,tv,lines,bubbles,dribbles,glass_parallax,parallax,brick,collage,seven,kenburns,cube,blur,book,rotate,domino,slices,blast,blinds,basic,basic_linear,fade,fly,flip,page,stack,stack_vertical",
	prev:"",
	next:"",
	duration:10*100,
	delay:51*100,
	width:1280,
	height:400,
	autoPlay:true,
	autoPlayVideo:false,
	playPause:false,
	stopOnHover:true,
	loop:true,
	bullets:0,
	caption:true,
	captionEffect:"traces",
	controls:true,
	controlsThumb:false,
	responsive:2,
	fullScreen:false,
	gestures:2,
	onBeforeStep:0
});
